export const extensions = [
  {
    id: 'datauri-analyzer',
    name: 'DataURI Media Analyser',
    description: 'Analyse DataURI files to get usefull information out of them.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
    gradient: 'from-cyan-400 to-blue-500',
    downloadUrl: '#',
  },
  {
    id: 'safe-area-finder',
    name: 'Find Safest Area',
    description: 'A tool for games to find the safest area to teleport a user to if their inside of somthing',
    thumbnail: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&h=300&fit=crop',
    gradient: 'from-emerald-400 to-teal-500',
    downloadUrl: '#',
  },
  {
    id: 'mic-recorder',
    name: 'Microphone Recorder',
    description: 'Literally just the name.',
    thumbnail: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=300&fit=crop',
    gradient: 'from-fuchsia-500 to-purple-600',
    downloadUrl: '#',
  },
  {
    id: 'random-game',
    name: 'Random Game extension',
    description: 'A random extension I made for a game may be usefull for finding stuff related to money values',
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    gradient: 'from-orange-400 via-rose-400 to-pink-500',
    downloadUrl: '#',
  },
  {
    id: 'color-tools',
    name: 'Color Tools',
    description: 'Simple extension for generating random hex codes, testing if a certan color is actualy real & other things',
    thumbnail: 'https://images.unsplash.com/photo-1525909002-1b05e0c869d8?w=400&h=300&fit=crop',
    gradient: 'from-pink-500 via-purple-500 to-indigo-500',
    downloadUrl: '#',
  },
  {
    id: 'ultimate-utility',
    name: 'ULTIMATE UTILITY',
    description: 'An extension with a rediculous amount of blocks that all just do random utility things.',
    thumbnail: null, // Will show a custom designed fallback
    gradient: 'from-red-500 to-orange-500',
    downloadUrl: '#',
  },
  // {
  //  id: 'unknown-1',
  //  name: 'Unknown Extension',
  //  description: 'Mystery extension waiting to be discovered',
  //  thumbnail: null,
  //  gradient: 'from-slate-700 to-slate-900',
  //  downloadUrl: '#',
  //},
  //{
  //  id: 'unknown-2',
  //  name: 'Unknown Extension',
  //  description: 'Another mysterious extension',
  //  thumbnail: null,
  //  gradient: 'from-slate-600 to-slate-800',
  //  downloadUrl: '#',
  //},
];
